# Part of place_ir. Licensed under AGPL-3.0.
"""Iran's places, taken in from the bundle this module ships.

data/ is a place bundle (place_graph/tools/bundle.py): places.csv, aliases.csv, links.csv
and manifest.json, made OUTSIDE Odoo from an OpenStreetMap extract (ODbL 1.0, © OpenStreetMap
contributors) by place_graph/tools/osm_import.py. Odoo does not read a map; it takes the
bundle in with place_graph's bulk loader:

  - on install, in seconds rather than the minutes the ORM needed;
  - on every update of this module, where an unchanged bundle costs one hash and a changed
    one loads only its difference;
  - never over what a person here decided: rows staff added or ratified (the overlay), and
    fields staff changed on an imported row, are left as they are.
"""
import os

from odoo import api, models

MODULE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLE_DIR = os.path.join(MODULE_DIR, 'data')


class PlaceNode(models.Model):
    _inherit = 'place.node'

    @api.model
    def _place_ir_sync(self):
        """Called by data/place_ir_data.xml on install and on every update of place_ir."""
        return self.sudo().load_bundle(BUNDLE_DIR)

    @api.model
    def load_country_data(self, force=True):
        """Take the shipped bundle in again, whether or not it changed -- for staff after the
        files were regenerated by hand. Kept under its old name, which the README taught."""
        return self.load_bundle(BUNDLE_DIR, force=force)
